server:
  port: 8080

logging:
  level:
    com.aigateway: DEBUG
  pattern: "[Gateway %d{HH:mm:ss}] %msg%n"

spring:
  config:
    import:
      - classpath:model.yml

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
